/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:c28fbe78-01dc-461e-bb64-55fabca0f4e2",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_u8BcYNBd9",
    "aws_user_pools_web_client_id": "2ovdd6cbue7pg9g956k2sbbc9l",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://4idtx66xybdqnh5yq25evjwuxa.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-c5g2suwmsvdptjlhelgvuf2w5e",
    "aws_user_files_s3_bucket": "amplifyappe7c02f6e1c264d6f938ea9f0f940be5c155842-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
